# =========================
# EQUIPOS DEL TORNEO
# =========================

TOURNAMENT_TEAMS = [
    "Ajax",
    "Real Sociedad",
    "Boca Juniors",
    "RB Leipzig",
    "Rangers",
    "FC Lorient",
    "Villarreal FC",
    "Copenhagen FC",
    "Napoli",
    "Aston Villa",
    "PSV Eindhoven",
    "River Plate",
    "Borussia Dortmund",
    "Real Betis",
    "PAOK FC",
    "Manchester City",
    "Newells",
    "Lanus",
    "Fenerbahce",
    "FC Barcelona",
    "Athletic Club",
    "OGC Niza",
    "Torino",
    "RC Lens",
    "Dinamo de Zagreb",
    "AZ Alkmaar",
    "Braga",
    "West Ham UTD",
    "Cagliari",
    "Union Berlin",
    "Olimpiacos",
    "Crystal Palace",
    "Inter de Milan",
    "FC Twente",
    "Valencia FC",
    "RB Salzburgo",
    "Everton",
    "Slavia de Praga",
    "Roma",
    "KRC Genk",
    "Leeds",
    "Rayo Vallecano",
    "Bayer Leverkusen",
    "Rosario Central",
    "Sevilla",
    "Stade Rennais FC",
    "Hamburgo",
    "Sparta de Praga",
    "FC Porto",
    "Fulham",
    "Hellas Verona",
    "Celtic",
    "Nottingham Forest",
    "Paris FC",
    "Liverpool",
    "Udinese",
    "Independiente",
    "Besiktas",
    "Getafe FC",
    "Lazio",
    "KAA Gent",
    "Chelsea",
    "Wolves",
    "Feyenoord",
    "Real Madrid",
    "AJ Auxerre",
    "Newcastle UTD",
    "O.Marsella",
    "Alaves",
    "VFB Stuttgart",
    "Panatinaikos",
    "Benfica",
    "Brighton",
    "FC Augsburg",
    "Genoa",
    "RCD Mallorca",
    "R.Union ST.-G",
    "AC Milan",
    "Sunderland",
    "Girona FC",
    "SC Freiburg",
    "Toulouse",
    "Racing Club",
    "Atletico de Madrid",
    "FC Koln",
    "ST Pauli",
    "Shaktar Donestsk",
    "Brentford",
    "Parma",
    "Olimpique Lyon",
    "VFL Wolfsburg",
    "Elche",
    "AFC Bournemouth",
    "FC Bayern Munchen",
    "Malmo FF",
    "Juventus",
    "Le Havre AC",
    "Sporting CP",
    "Arsenal",
    "Pisa",
    "AS Monaco",
    "RC Estrasburgo",
    "TSG Hoffenheim",
    "Anderlecht",
    "Burnley",
    "Spurs",
    "Como 1907",
    "AEK Atenas",
    "FSV Mainz 05",
    "Dinamo de kiev",
    "Lecce",
    "Stade Brestois",
    "Galatasaray",
    "Bergamo",
    "Viktoria Pilzen",
    "Estudiantes",
    "Fiorentina",
    "PSG",
    "Angers SCO",
    "FC Nantes",
    "Oviedo",
    "CA Osasuna",
    "Famalicio",
    "FC Metz",
    "Borussia M'gladbach",
    "SV Werder Bremen",
    "Apoel",
    "RC Celta",
    "LOSC Lille",
    "RCD Espayol",
    "Heidenheim",
    "Club Brujas",
    "Manchester United",
    "Sassuolo",
    "Utrecht",
    "Frankfurt",
    "Bolonia",
    "Cremonense",
    "Levante"
]
# =========================
# JUGADORES LEYENDA
# =========================

DIAMOND_LEGENDS = [
    "Maradona",
    "Messi",
    "Puskas",
    "Beckenbauer",
    "Pele",
    "Yahsin PT",
    "Cruyff",
    "Ronaldo",
    "Maldini",
    "Ronaldinho",
    "Zidane",
    "Charlton",
    "Zico",
    "Van basten",
    "Eusebio",
    "Rivaldo",
    "R.Baggio",
    "G.Muller",
    "Pirlo",
    "Xavi",
    "Henry",
    "Gullit",
    "Iniesta",
    "Garrincha",
    "Baresi",
    "Cafu",
    "Ibra",
    "C.Ronaldo",
    "Del piero",
    "Casillas PT",
    "Matthaus",
    "R.Carlos",
    "Best"
]

GOLD_LEGENDS = [
    "Neymar",
    "Rummenigge",
    "Totti",
    "Chiellini",
    "Socrates",
    "Jairzinho",
    "Stoickov",
    "Carlos alberto",
    "Raul",
    "Figo",
    "H.Sanchez",
    "Butragueno",
    "Puyol",
    "Eto'o",
    "Buffon",
    "Nedved",
    "Kaka",
    "Zanetti",
    "Vieira",
    "Nesta",
    "Drogba",
    "Bergkamp",
    "Morientes",
    "Vialli",
    "Lucio",
    "Kohler",
    "Papin",
    "Abedi Pele",
    "Ginola",
    "Beckham",
    "Shevchenko",
    "Dalglish",
    "Shearer",
    "Cantona",
    "Cannavaro",
    "L.suarez",
    "Terry",
    "T.Adams",
    "Law",
    "Marcelo",
    "Hagi",
    "Koeman",
    "Laudrup",
    "Riquelme",
    "Hierro",
    "Lahm",
    "Ribery",
    "Schweinsteiger",
    "Blanc",
    "Thuram",
    "Bale",
    "Van nistelrroy",
    "Ferdinand",
    "Moore",
    "Litmanen",
    "Futre",
    "Forlan",
    "D.Milito",
    "Mascherano",
    "Maicon",
    "Sneijder",
    "Francescoli",
    "Di natale",
    "Klose",
    "M.gomez",
    "Okocha",
    "Lizarazu",
    "R.Marquez",
    "Berbatov",
    "Kompany",
    "Tevez",
    "Carvalho",
    "Scholes",
    "Owen",
    "Van der sar PT",
    "Desailly",
    "Voller"
]

SILVER_LEGENDS =[
    "Ze roberto",
    "Wright",
    "Pires",
    "Marchisio",
    "Zola",
    "Hamsik",
    "Makelele",
    "Lampard",
    "Kewell",
    "Xabi Alonso",
    "F.Torres",
    "Joe Cole",
    "H.son",
    "Barnes",
    "I.rush",
    "Yaya Toure",
    "Stam",
    "Vidic",
    "Aimar",
    "Suker",
    "Luis Suarez",
    "J.Campos PT",
    "Kluivert",
    "Rui costa",
    "Mcmanaman",
    "Rijkaard",
    "Petit",
    "Benzema",
    "I.cordoba",
    "Nakata",
    "De rossi",
    "Schmeichel PT",
    "Cech PT"
]

BRONZE_LEGENDS = [
    "Noor",
    "Al owairan",
    "Reus",
    "Gervinho",
    "Howard PT",
    "Cahill",
    "Ibarbo",
    "Crouch",
    "Doumbia",
    "J.Alba",
    "Dempsey",
    "Quaresma",
    "Beasley",
    "Dudek PT",
    "King",
    "Govou",
    "Al jaber",
    "Roy Keane",
    "Park ji Sung",
    "Zambrotta",
    "Capdevila",
    "M.Salgado",
    "Brolin",
    "Solskajaer",
    "Guti",
    "Kanu",
    "Smolarek",
    "Riise",
    "Donovan",
    "Kuyt",
    "Carragher",
    "Cha Bum Kum",
    "L.Hernandez",
    "Ramires",
    "Essien",
    "Cole",
    "Busquets",
    "Crespo",
    "Veron",
    "Campbell",
    "Gattuso",
    "Rosicky",
    "Ljunberg",
    "Larsson",
    "T.Muller",
    "Matuidi",
    "Giuly",
    "Robbie Keane"
]
# =========================
# RULETAS
# =========================
# =========================
# EQUIPOS DEL TORNEO
# =========================




# =========================
# EQUIPOS ESPECIALES PARA EVENTOS
# =========================

TEAMS_5_STARS = [
    "Real Madrid",
    "FC Barcelona",
    "PSG",
    "Liverpool",
    "Manchester City",
    "Arsenal",
    "Bayern Munich"
]

TEAMS_4_5_STARS = [
    "Atlético Madrid",
    "Newcastle United",
    "Napoli",
    "Borussia Dortmund",
    "Tottenham Hotspur",
    "Chelsea",
    "Aston Villa",
    "Manchester United",
    "Bayer Leverkusen"
]



# =========================
# RULETA DE OPCIONES
# =========================

OPTION_ROULETTE = [
    "Comodín Plata",
    "Tirar Ruleta Plata",
    "Pierde un Medio",
    "Fichar un jugador Normal",
    "Tirar Ruleta Oro",
    "Fichar jugador equipo 5*",
    "Comodín Plata",
    "Fichar un Atacante",
    "Tirar Ruleta Plata",
    "Comodín Diamante",
    "Pierde un Def/Portero",
    "Comodín Oro",
    "Tirar Ruleta Bronce",
    "Fichar un Def/Portero",
    "Tirar Ruleta Bronce",
    "Pierde un jugador Normal",
    "Comodín Bronce",
    "Fichar jugador equipo 4.5*",
    "Pierde un Atacante",
    "Comodín Oro",
    "Tirar Ruleta Oro",
    "Tirar Ruleta Plata",
    "Tirar Ruleta Bronce",
    "Fichar un Medio",
    "Tirar Ruleta Diamante",
    "Comodín Bronce"
]
